name: Build APK

on:
  push:
    branches:
      - main  # Измени на свою ветку, если нужно

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
              libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

      - name: Установка Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Кеширование .buildozer
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Сборка APK
        run: buildozer android debug

      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-APK
          path: bin/*.apk
