name: Build APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install buildozer

      - name: Сборка APK
        run: buildozer android debug

      - name: Загрузка APK в артефакты
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
